CREATE DATABASE IF NOT EXISTS cropdb;

USE cropdb;

CREATE TABLE `croprecommend` (
  `N` int(11) NOT NULL,
  `P` int(11) NOT NULL,
  `K` int(11) NOT NULL,
  `temperature` float NOT NULL,
  `humidity` float NOT NULL,
  `ph` float NOT NULL,
  `rainfall` float NOT NULL,
  `label` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  KEY `__UNORDERED` () USING CLUSTERED COLUMNSTORE
  , SHARD KEY () 
) AUTOSTATS_CARDINALITY_MODE=INCREMENTAL AUTOSTATS_HISTOGRAM_MODE=CREATE AUTOSTATS_SAMPLING=ON SQL_MODE='STRICT_ALL_TABLES'
